version: "3.6"
services:
  redis:
    image: redis:4-alpine
#    ports:
#      - target: 6379
#        protocol: tcp
#        mode: host
    volumes:
      - /home/storage/opt/redis:/data
#      - /opt/redis:/data
  postgres:
    image: postgres:10
    # make sure that your db local storage will be located on one node. If you have several nodes
    # you could use this vvv to pin the container
    # deploy:
    #   placement:
    #     constraints: [node.hostname == node-name]
    volumes:
      # change this vvv
      - /home/storage/opt/postgres/data:/var/lib/postgresql/data
#      - /opt/postgres/data:/var/lib/postgresql/data
    environment:
      DB_NAME: mentoring
      DB_USERNAME: mentoring
      DB_USERPASS: /run/secrets/db_userpass
    configs:
      - source: update-postgres-configs.sh
        target: /docker-entrypoint-initdb.d/update-postgres-configs.sh
        mode: 0555
      - source: init-mentoring-user-db.sh
        target: /docker-entrypoint-initdb.d/init-mentoring-user-db.sh
        mode: 0555
    secrets:
#      - postgres_admin_password
      - db_userpass
  mentoring:
    image: mentoring:latest
#    entrypoint: /migrate
#    command: bundle exec cap production deploy
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # wait till postgres loads
    command: sh -c './script/wait-for postgres:5432 -- ./script/run'
#    volumes:
#      - .:/mentoring
#    pid: "host"
    ports:
      - "3030:3000"
    depends_on:
      - redis
      - postgres
    environment:
      HTTP_HOST: localhost
      REDIS_HOST: redis
      DB_HOST: postgres
#      DB_HOST: postgres
      DB_NAME: mentoring
      DB_USERNAME: mentoring
#      DB_USERNAME: mentoring
#      DB_USERPASS: /run/secrets/postgres_admin_password
      DB_USERPASS: /run/secrets/db_userpass
      # will be used as a mail transport
      GMAIL_USER: sunlark.tests@gmail.com
#      GMAIL_USER: <gmail account here>
      GMAIL_PASS: /run/secrets/gmail_password
      # these two uses one time while db initialization
      MAILER_SENDER: '"Программа Детский дом" <sunlark.tests@gmail.com>'
#      MAILER_SENDER: '"Программа Детский дом" <nastavnichestvo@inbox.ru>'
      MAILER_TOKEN: /run/secrets/mailer_token
      ADMIN_EMAIL: newsiberian2015@yandex.ru
#      ADMIN_EMAIL: <admin email here>
      ADMIN_PASSWORD: /run/secrets/admin_password
      # must be generated via `bin/rails secrets`
      SECRET_KEY_BASE: /run/secrets/secret_key_base
#      LANG: "en_US.UTF-8"
#    configs:
#      - source: migrate
#        target: /migrate
#        mode: 0540
#      - source: run
#        target: /run
#        mode: 0540
    secrets:
#      - postgres_admin_password
      - db_userpass
      - gmail_password
#      - admin_password
      - secret_key_base
configs:
  migrate.sh:
    file: script/migrate
  run.sh:
    file: script/run
  init-mentoring-user-db.sh:
    file: script/init-mentoring-user-db.sh
  update-postgres-configs.sh:
    file: script/update-postgres-configs.sh
secrets:
  # these files must be in the <app>/secrets folder before building an image
#  postgres_admin_password:
#    file: secrets/postgres_admin_password
  db_userpass:
    file: secrets/db_userpass
  gmail_password:
    file: secrets/gmail_password
  admin_password:
    file: secrets/admin_password
  secret_key_base:
    file: secrets/secret_key_base
  mailer_token:
    file: secrets/mailer_token
